const { db } = require("../config/firebaseConfig");

class User {
    constructor(id, username, email, country_code, phone_number, flag, profile_pic, role, createdAt, updatedAt) {
        this.id = id; // represents the id generated by the firestore
        this.username = username;
        this.email = email;
        this.country_code = country_code;
        this.phone_number = phone_number;
        this.flag = flag;
        this.profile_pic = profile_pic;
        this.role = role;
        this.profile_pic = profile_pic;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}

module.exports = User;